"""описание изменений

Revision ID: db29145843f5
Revises: 17dcc2b3196d
Create Date: 2026-01-11 17:42:01.414916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db29145843f5'
down_revision: Union[str, Sequence[str], None] = '17dcc2b3196d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('books', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Fantasy'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Fantasy'"))
    op.alter_column('books', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###
